# Generated by Django 6.1.1 on 2026-09-07 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(db_index=True, max_length=400, unique=True)),
                ('subject', models.CharField(blank=True, max_length=1000)),
                ('sender', models.CharField(blank=True, max_length=400)),
                ('recipient', models.CharField(blank=True, max_length=400)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('body_text', models.TextField(blank=True)),
                ('language', models.CharField(default='en', max_length=8)),
                ('processing_status', models.CharField(choices=[('QUEUED', 'Queued'), ('PROCESSING', 'Processing'), ('READY', 'Ready for review'), ('FAILED', 'Failed')], db_index=True, default='QUEUED', max_length=20)),
                ('review_status', models.CharField(choices=[('PENDING', 'Pending review'), ('ACCEPTED', 'Accepted'), ('OVERRIDDEN', 'Overridden')], db_index=True, default='PENDING', max_length=20)),
                ('processing_ms', models.IntegerField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('headers', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['processing_status', 'review_status'], name='inbox_messa_process_386cea_idx')],
            },
        ),
        migrations.CreateModel(
            name='Extraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('ICSR', 'Safety Report'), ('PQC', 'Quality Complaint'), ('MI', 'Info Request'), ('NOT_RELEVANT', 'Not Relevant')], max_length=20)),
                ('narrative', models.TextField(blank=True)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('completeness', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extractions', to='inbox.message')),
            ],
            options={
                'unique_together': {('message', 'category')},
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.CharField(db_index=True, max_length=400)),
                ('file_name', models.CharField(max_length=500)),
                ('media_type', models.CharField(blank=True, max_length=200)),
                ('flavour', models.CharField(choices=[('digital', 'Digital PDF'), ('scanned', 'Scanned / handwritten'), ('article', 'Published article'), ('non_english', 'Non-English'), ('email_body', 'Email body'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('language', models.CharField(default='en', max_length=8)),
                ('page_count', models.IntegerField(default=0)),
                ('processed', models.BooleanField(default=True)),
                ('extracted_text', models.TextField(blank=True)),
                ('tables', models.JSONField(blank=True, default=list)),
                ('images', models.JSONField(blank=True, default=list)),
                ('doc_metadata', models.JSONField(blank=True, default=dict)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('summary', models.TextField(blank=True)),
                ('looks_relevant', models.BooleanField(blank=True, null=True)),
                ('relevance_reason', models.TextField(blank=True)),
                ('summary_confidence', models.FloatField(blank=True, null=True)),
                ('ocr_confidence', models.FloatField(blank=True, null=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='inbox.message')),
            ],
            options={
                'unique_together': {('message', 'document_id')},
            },
        ),
        migrations.CreateModel(
            name='ReviewAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('ACCEPT', 'Accepted AI output'), ('OVERRIDE_FIELD', 'Overrode a field value'), ('OVERRIDE_CATEGORY', 'Overrode a category'), ('REJECT', 'Rejected as not relevant'), ('COMMENT', 'Added a comment')], max_length=30)),
                ('reviewer', models.CharField(default='demo-reviewer', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('field_name', models.CharField(blank=True, max_length=100)),
                ('original_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=20)),
                ('note', models.TextField(blank=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_actions', to='inbox.message')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExtractedField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('value', models.TextField(default='Not stated')),
                ('confidence', models.FloatField(default=0.0)),
                ('source_document', models.CharField(blank=True, max_length=500)),
                ('source_page', models.IntegerField(blank=True, null=True)),
                ('source_quote', models.TextField(blank=True)),
                ('quote_verified', models.BooleanField(default=False)),
                ('extraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='inbox.extraction')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('extraction', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('ICSR', 'Safety Report'), ('PQC', 'Quality Complaint'), ('MI', 'Info Request'), ('NOT_RELEVANT', 'Not Relevant')], max_length=20)),
                ('applies', models.BooleanField(default=False)),
                ('confidence', models.FloatField(default=0.0)),
                ('reason', models.TextField(blank=True)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classifications', to='inbox.message')),
            ],
            options={
                'ordering': ['-confidence'],
                'unique_together': {('message', 'category')},
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('CLASSIFY', 'Classification'), ('EXTRACT', 'Field extraction'), ('OCR', 'Scanned page transcription'), ('IMAGE', 'Image description'), ('SUMMARY', 'Document summary'), ('SCREEN', 'Literature screening')], db_index=True, max_length=20)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('is_stub', models.BooleanField(default=False)),
                ('prompt_sha256', models.CharField(blank=True, max_length=64)),
                ('prompt_chars', models.IntegerField(default=0)),
                ('latency_ms', models.FloatField(default=0.0)),
                ('succeeded', models.BooleanField(default=True)),
                ('error', models.TextField(blank=True)),
                ('response_summary', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='inbox.document')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='inbox.message')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='inbox_audit_event_t_c8ca0d_idx')],
            },
        ),
    ]
