# Generated by Django 6.1.1 on 2026-09-07 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractedfield',
            name='value',
            field=models.CharField(default='Not stated', max_length=2000),
        ),
    ]
